version: '3.8'

services:
  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"

  backend:
    # O build agora aponta para a pasta raiz onde está o Dockerfile
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - frontend